module.exports = {
    "plugins": ["mocha"],
    "rules": {
        "mocha/handle-done-callback": "error",
        "mocha/max-top-level-suites": "error",
        "mocha/no-exclusive-tests": "error",
        "mocha/no-global-tests": "error",
        "mocha/no-hooks": "off",
        "mocha/no-hooks-for-single-case": "error",
        "mocha/no-identical-title": "error",
        "mocha/no-mocha-arrows": "off",
        "mocha/no-nested-tests": "error",
        "mocha/no-pending-tests": "off",
        "mocha/no-return-and-callback": "off",
        "mocha/no-sibling-hooks": "error",
        "mocha/no-skipped-tests": "error",
        "mocha/no-synchronous-tests": "off",
        "mocha/no-top-level-hooks": "error",
        "mocha/valid-suite-description": "off",
        "mocha/valid-test-description": "off",
    },
};
